#!/bin/bash


CURRENCY=$(dialog --menu "Выберите валюту:" 15 50 4 \
"USD" "Доллар США" \
"EUR" "Евро" \
"JPY" "Японская иена" \
"GBP" "Фунт стерлингов" 3>&1 1>&2 2>&3)

case $CURRENCY in
    "USD")
        RATE="75.00"
        ;;
    "EUR")
        RATE="85.00"
        ;;
    "JPY")
        RATE="0.70"
        ;;
    "GBP")
        RATE="100.00"
        ;;
esac

dialog --msgbox "Котировка для $CURRENCY: $RATE" 7 60
