#!/bin/bash

# Директория для проверки
directory="./"

# Ищем скрипты с расширением .sh в указанной директории
script_file=$(find "$directory" -maxdepth 1 -name "*.sh")

# Проверяем, найден ли скриптовый файл, и если найден — выполняем
if [[ -n "$script14" ]]; then
    echo "Найден скрипт: $script14"
    bash "$script14"
else
    echo "Скриптовый файл не найден."
fi
